spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_social?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: home
    password: home
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy:  org.hibernate.cfg.ImprovedNamingStrategy
  properties:
    hibernate: 
         dialect: